channels:
  - conda-forge
dependencies:
  - xarray
  - cmocean
  - seaborn
  - jupyterlab
  - black
  - dask
  - netcdf4
  - scipy
  - bottleneck
  - h5netcdf
  - cftime
  - cartopy
  - matplotlib
  - cdo
  - python-cdo
  - tqdm
  - ca-certificates
  - certifi
  - openssl
  - xesmf
  - jupyter-black
variables:
  HDF5_USE_FILE_LOCKING: 'FALSE'
